//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int Id { get; set; }
        public Nullable<int> IdDH { get; set; }
        public Nullable<int> IdSP { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<int> IdCuaHang { get; set; }
    }
}
