//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int Id { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> IsHienThi { get; set; }
        public Nullable<int> IdSP { get; set; }
    }
}
