//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> IdKH { get; set; }
        public string DiaChiGiao { get; set; }
        public string SDT { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    }
}
