//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int Id { get; set; }
        public string TenSP { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> IdTK { get; set; }
        public Nullable<int> IdDiaPhuong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> HSD { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> IdLoai { get; set; }
    }
}
